"""Init revision.

Revision ID: 14f37c9b7479
Revises:
Create Date: 2022-05-21 15:30:23.570611

"""
from typing import Optional

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14f37c9b7479"
down_revision: Optional[str] = None
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade() -> None:
    """Upgrade actions that must be performed when upgrading the database to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pb_servers",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("host", sa.String(length=256), nullable=False),
        sa.Column("port", sa.SmallInteger(), nullable=False),
        sa.Column("max", sa.SmallInteger(), nullable=False),
        sa.Column("alias", sa.String(length=256), nullable=False),
        sa.Column("owner", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="servers_id_pk"),
        sa.UniqueConstraint("alias", name="sever_unique_alias"),
        sa.UniqueConstraint("host", "port", name="ip"),
    )
    op.create_table(
        "pb_pings",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("host", sa.String(length=256), nullable=False),
        sa.Column("port", sa.SmallInteger(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("players", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["host"], ["pb_servers.host"], name="server_host_to_ping_host"),
        sa.ForeignKeyConstraint(["port"], ["pb_servers.port"], name="server_port_to_ping_port"),
        sa.PrimaryKeyConstraint("id", name="pings_id_pk"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade actions that must be performed when downgrading the database from this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pb_pings")
    op.drop_table("pb_servers")
    # ### end Alembic commands ###
