name: Deploy

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dialect: ['sqlite', 'mysql', 'postgresql']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: perchunpak
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: perchunpak/pingerbot
        flavor: |
          latest=false
        tags: |
          type=semver,pattern={{version}},enable=${{ matrix.dialect == 'sqlite' }}
          type=semver,pattern={{version}},suffix=-${{ matrix.dialect }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: dialect=${{ matrix.dialect }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
